"""
自动开发模块 - 基于需求生成AI解决方案
实际生产中：调用Claude/GPT-4生成代码 → 测试 → 部署
"""
import asyncio
import json
import os
from datetime import datetime
from pathlib import Path
import httpx

WORKSPACE = Path(__file__).parent.parent.parent / "workspace"
WORKSPACE.mkdir(parents=True, exist_ok=True)

async def auto_build(demand, config: dict) -> dict:
    """自动开发方案"""
    project_id = f"{demand.source}-{hash(demand.title) & 0xFFFFFF:06x}"
    project_dir = WORKSPACE / project_id
    project_dir.mkdir(parents=True, exist_ok=True)

    # 1. 生成技术方案 (调用LLM)
    proposal = await generate_proposal(demand, config)

    # 2. 生成代码骨架
    scaffold = await generate_scaffold(demand, config)

    # 3. 写文件
    (project_dir / "proposal.md").write_text(proposal, encoding="utf-8")
    (project_dir / "main.py").write_text(scaffold, encoding="utf-8")
    (project_dir / "README.md").write_text(
        f"# {demand.title}\n\n"
        f"Auto-generated by AI Autonomy Platform\n\n"
        f"- 来源: {demand.url}\n"
        f"- 分类: {demand.category}\n"
        f"- 价值: ${demand.estimated_value_usd:.0f}\n"
        f"- 评分: {demand.score}/100\n\n"
        f"## 交付清单\n"
        f"- [x] 技术方案 proposal.md\n"
        f"- [x] 代码骨架 main.py\n"
        f"- [ ] 客户确认细节\n"
        f"- [ ] 全量开发 + 测试\n"
        f"- [ ] 部署 + 收款\n",
        encoding="utf-8"
    )

    return {
        "demand_id": demand.id,
        "project_id": project_id,
        "project_dir": str(project_dir),
        "files": ["proposal.md", "main.py", "README.md"],
        "estimated_dev_hours": max(8, demand.score // 5),
        "quoted_price_usd": demand.estimated_value_usd,
        "next_steps": [
            "客户确认需求细节",
            "签署Creem支付协议",
            "启动开发Sprint",
            "14天内交付MVP",
        ]
    }

async def generate_proposal(demand, config: dict) -> str:
    """生成技术方案"""
    # 优先使用 DeepSeek (便宜), 其次 OpenAI
    api_key = config.get("deepseek_api_key") or config.get("openai_api_key")
    base_url = "https://api.deepseek.com" if config.get("deepseek_api_key") else "https://api.openai.com/v1"
    model = "deepseek-chat" if config.get("deepseek_api_key") else "gpt-4o-mini"

    prompt = f"""为以下客户需求撰写一份专业的技术方案(中文, 300字以内):

需求标题: {demand.title}
需求描述: {demand.description}
分类: {demand.category}
来源: {demand.url}

方案需包含:
1. 技术架构 (用哪些AI模型/API)
2. 交付里程碑 (分3阶段)
3. 价格: ${demand.estimated_value_usd:.0f} USD
4. 工期: 14天MVP + 30天完整版

请用专业的语气, 像发给客户看的一样。"""

    if not api_key:
        return f"""# 技术方案: {demand.title}

## 概述
基于您的需求{demand.title}，我们提供完整的AI解决方案。

## 技术栈
- 后端: Python + FastAPI
- AI模型: GPT-4o / Claude 3.5 / 开源LLM
- 前端: Next.js + TailwindCSS
- 部署: AWS / Vercel / 阿里云

## 里程碑
**Phase 1 (Day 1-3)**: 需求确认 + 架构设计
**Phase 2 (Day 4-10)**: MVP开发 + 内部测试
**Phase 3 (Day 11-14)**: 客户验收 + 部署上线

## 报价
USD ${demand.estimated_value_usd:.0f} (含源码 + 3个月维护)

## 支付方式
Creem (国际信用卡) / 支付宝 (国内) / USDT
50%启动 + 50%验收

---
Auto-generated by AI Autonomy Platform
{datetime.now().isoformat()}
"""

    try:
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                f"{base_url}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.7,
                }
            )
            if r.status_code == 200:
                content = r.json()["choices"][0]["message"]["content"]
                return f"# 技术方案: {demand.title}\n\n{content}\n\n---\nAuto-generated {datetime.now().isoformat()}\n"
    except Exception as e:
        pass
    return f"# 技术方案: {demand.title}\n\n[方案生成失败, 请手动补充]\n\nAPI key未配置或调用失败。\n"

async def generate_scaffold(demand, config: dict) -> str:
    """生成代码骨架"""
    return f'''"""
{demand.title}
Auto-generated scaffold for: {demand.category}
需求来源: {demand.url}
"""
import os
import httpx
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="{demand.title[:50]}")

class Request(BaseModel):
    query: str
    context: dict = {{}}

class Response(BaseModel):
    result: str
    metadata: dict = {{}}

@app.post("/api/process")
async def process(req: Request):
    """核心业务逻辑"""
    # TODO: 根据需求实现
    # 1. 调用AI模型处理
    # 2. 业务逻辑
    # 3. 返回结果
    return Response(
        result=f"Processed: {{req.query}}",
        metadata={{"source": "{demand.source}", "category": "{demand.category}"}}
    )

@app.get("/")
async def root():
    return {{"status": "running", "title": "{demand.title}"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
'''